name: Releasing

on:
  push:
    branches:
      - main
    paths:
      - 'helm/kubesleeper/**'
      - 'static/**'
      - 'src/**'
      - 'Dockerfile'
      - 'Cargo.toml'


jobs:
  version:
      runs-on: ubuntu-latest
      outputs:
        docker_version: ${{ steps.version.outputs.docker_version }}
        helm_version: ${{ steps.version.outputs.helm_version }}
      steps:
        - name: Code Checkout
          uses: actions/checkout@v4
  
        - name: Check if Git tag already exists
          id: version
          run: |
            BIN_VERSION=$(cargo metadata --no-deps --format-version 1 | jq -r '.packages[0].version')
            HELM_VERSION=$(grep '^version:' helm/kubesleeper/Chart.yaml | awk '{print $2}' | tr -d '"')
            DOCKER_VERSION=$BIN_VERSION
            
            if git ls-remote --tags origin "refs/tags/${HELM_VERSION}" | grep -q "${HELM_VERSION}"; then
              echo "Error: Tag '$HELM_VERSION' already exists"
              exit 1
            fi
            echo "docker_version=$DOCKER_VERSION"   >> "$GITHUB_OUTPUT"
            echo "helm_version=$HELM_VERSION" >> "$GITHUB_OUTPUT"
          
          
  build-kubesleeper:
    runs-on: ubuntu-latest
    needs: version
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Build kubesleeper binary
        id: build
        run: |
          docker build --target binary-export --output type=local,dest=./dist .
    
      - name: Upload Artifact (Cargo.toml, kubesleeper binary)
        uses: actions/upload-artifact@v4
        with:
          name: built-products
          path: |
            dist/kubesleeper
            Cargo.toml
          retention-days: 1

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          target: image
          context: ./
          push: true
          tags: |
            ghcr.io/kubesleeper/kubesleeper:latest
            ghcr.io/kubesleeper/kubesleeper:${{ needs.version.outputs.docker_version }}


  build-helm:
    runs-on: ubuntu-latest
    needs: version
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
      
      - name: Helm package
        run: |
            helm package helm/kubesleeper
        
      - name: Upload Artifact (helm chart)
        uses: actions/upload-artifact@v4
        with:
          name: helm-products
          path: |
            helm/kubesleeper/Chart.yaml
            kubesleeper-*.tgz
          retention-days: 1
          
          
  release:
    needs:
      - build-kubesleeper
      - build-helm
      - version
    runs-on: ubuntu-latest
    permissions:
      contents: write # for 'action-gh-release'

    steps:
      
      - name: Code Checkout
        uses: actions/checkout@v4
        with:
            token: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Download bin and image artifacts
        uses: actions/download-artifact@v4
        with:
          name: built-products
          path: .
          
      - name: Download helm artifacts
        uses: actions/download-artifact@v4
        with:
          name: helm-products
          path: .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.version.outputs.helm_version }}
          name: Release ${{ needs.version.outputs.helm_version }}
          files: |
            dist/kubesleeper
            kubesleeper-*.tgz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


